[workspace]
members = [
    ".", "mnn-bridge",
    "mnn-sys",
]

[package]
name = "mnn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
mnn-sys = { version = "0.1", path = "mnn-sys", features = [] }
thiserror = "1.0"
error-stack = { version = "0.5" }
oneshot = "0.1"
tracing = { version = "0.1.40", optional = true }

[features]
metal = ["mnn-sys/metal"]
coreml = ["mnn-sys/coreml"]
vulkan = ["mnn-sys/vulkan"]
opencl = ["mnn-sys/opencl"]
opengl = ["mnn-sys/opengl"]
crt_static = ["mnn-sys/crt_static"]
# Disable mnn-threadpool to enable this
openmp = ["mnn-sys/openmp"] 
mnn-threadpool = ["mnn-sys/mnn-threadpool"]
sync = []
default = ["mnn-threadpool", "sync", "parse"]
parse = []
tracing = ["dep:tracing"]

[dev-dependencies]
anyhow = "1.0"
bytemuck = "1.17"
clap = { version = "4.5", features = ["derive"] }
