[workspace]
members = [
    ".",
    "mnn-sys",
    "runner",
]

[package]
name = "mnn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
castaway = "0.2.3"
libc = "0.2.155"
mnn-sys = { version = "0.1.0", path = "mnn-sys", features = [] }
thiserror = "1.0.63"
error-stack = { version = "0.5.0" }
oneshot = "0.1.8"

[features]
metal = ["mnn-sys/metal"]
coreml = ["mnn-sys/coreml"]
vulkan = ["mnn-sys/vulkan"]
opencl = ["mnn-sys/opencl"]
opengl = ["mnn-sys/opengl"]
# Disable mnn-threadpool to enable this
openmp = ["mnn-sys/openmp"] 
mnn-threadpool = ["mnn-sys/mnn-threadpool"]
default = ["mnn-threadpool"]
parse = []

[dev-dependencies]
anyhow = "1.0.86"
bytemuck = "1.17.1"
clap = { version = "4.5.9", features = ["derive"] }
