[package]
name = "mnn-sync"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
error-stack = "0.5.0"
flume = { version = "0.11.0", default-features = false, features = [
  "eventual-fairness",
  "nanorand",
] }
mnn = { version = "0.1.0", path = ".." }
oneshot = "0.1.8"
