[package]
name = "mnn-sys"
version = "0.1.0"
edition = "2021"

[build-dependencies]
anyhow = "1.0.86"
autocxx-build = { version = "0.27.0" }
bindgen = "0.69.4"
cc = { version = "1.1.5", features = ["parallel"] }
cmake = { git = "https://github.com/blonteractor/cmake-rs", features = ["parallel"] }
diffy = "0.4.0"
fs_extra = "1.3.0"
tap = "1.0.1"

[features]
vulkan = []
metal = []
coreml = ["metal"]

[dependencies]
autocxx = "0.27.0"
bindgen = "0.69.4"
cxx = { version = "1.0.124", features = ["c++14"] }

