[package]
name = "mnn-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
mnn = { version = "0.1.0", path = "..", default-features = false }
ndarray = { version = "0.16.1", optional = true }
opencv = { version = "0.92.3", default-features = false, optional = true }

[features]
ndarray = ["dep:ndarray"]
opencv = ["dep:opencv"]

default = ["ndarray"]
