name: Build

on:
  push:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"

    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: DeterminateSystems/flake-checker-action@main

    - name: Run `nix flake check`
      run: nix flake check

    - name: Run codecov
      run: nix --extra-experimental-features "nix-command flakes" build .#mnn-llvm-cov

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        flags: unittests
        name: codecov-mnn
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./result
        verbose: true

    - name: Generate docs
      run: nix build .#x86_64-linux.mnn-docs

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: result/share/doc/mnn

    - name: Deploy to gh-pages
      id: deployment
      uses: actions/deploy-pages@v4
